### ISSUE TITLE
"TypeError: o is undefined" in Firefox ver 124.0.2 (64-bit)

### ISSUE THREAD

**Issue by blindsamurai777** [houtianze/libby-audiobook-exporter-browser-extension#13] opened 2024-04-13 00:11 UTC
The add-on was working great yesterday, 4/11/2024, and for many weeks beforehand. The Firefox add-on is now broke. The add-on information page accessed via Add-ons Manager in Firefox shows the add-on received its last update on 2/11/2024, and I can confirm the add-on has worked as expected since then until now. When downloading a book today, 4/12/2024, the process will error-out early with the message "TypeError: o is undefined" --> "o" as in letter o. Maybe a simple typo in the source code?

Tested it out on previously downloaded books and new books. All result in the following:

Reloading Tab --> Completed
Waiting for State --> Check 2
"TypeError: o is undefined" --> Failed

![Picture1](https://github.com/houtianze/libby-audiobook-exporter-browser-extension/assets/166881305/d2776756-eb34-46fa-94cd-974d8ddb7f5a)

**Comment by mkgtu** [comment] 2024-04-14 01:28
Don't know what's going on. Have heard of some people having issues. But I just tried the Firefox extension and it successfully downloaded a book without any problems at all.

**Comment by blindsamurai777** [comment] 2024-04-14 02:02
Bizarre, indeed. I just tried downloading a book on an old laptop I had laying around. Didn't have Firefox on it, so did a fresh install of Firefox. No other add-ons installed. Only the Libby downloader. It worked, no problem. 

Tried it again on my main computer, which prompted this thread in the first place - still giving me the "TypeError: o is undefined" error. What could the difference be? Possibly related to cache/cookies/history, I'm guessing. Maybe conflicts with one of my others add-ons: Addblock Plus or uBlock Origin. I'll do some troubleshooting on my main computer and report my findings.

**Comment by mkgtu** [comment] 2024-04-14 03:27
For what it's worth, there
Is another method for downloading Libby audiobooks. It's a Telegram bot (Libby Audiobook Bot). I only mention this here  because I just tried it and successfully downloaded a book. So it still works. So if Libby has changed anything it's not affecting this bot:
https://github.com/joshuatly/libby_ab_bot

**Comment by NotKoalafied** [comment] 2024-04-14 04:43
Update:
I have now been able to remediate the issue in both Chrome and Firefox. I used different methods, so I will put some more info for each below. It's worth noting that for both methods I had to add my library card back by searching for the library and adding the number manually because copying from another device caused the issue to continue. Because I tried several things at once, I'm not sure which of them actually fixed the issue.

Firefox:
I don't use this browser regularly on the computer where I normally download, so I fully removed Firefox and tried again with a fresh installation with only the add-on for downloading being used.

Chrome:
I didn't want to fully refresh the browser, so I instead allowed 3rd party cookies and cleared the cookies for Libby.

**Comment by blindsamurai777** [comment] 2024-04-14 04:52
Thanks mkgtu. I was going to look into that bot, but I am no longer getting the TypeError. All good now. However, I'm hesitant to say the matter is _solved_, but I've narrowed the root-cause down to one of two possibilities. I strongly suspect it is related to the first possibility, which I will elaborate on momentarily. The good news is that It does not appear to be a Firefox issue or an issue with the add-on itself, because nothing worked to fix the error after a lot of painstaking troubleshooting (e.g., clearing cache/history, uninstalling add-ons, reinstalling Firefox). 

**Resolution (Temporary?)**
What did I do to rid myself of the error? I manually added my library cards, one-by-one, to my Libby desktop browser. Each time I added a card, I redownloaded a test file/book to confirm it worked.

**Possible Root-Causes:**
1. Syncing issues. I have my Libby desktop browser synced with my Libby mobile app. Been that way for a while. I generate the sync code from my mobile device and enter it into the desktop browser. I do my downloads from the desktop browser on a Windows 10 PC. I "reset everything" on my Libby desktop browser so many times as part of troubleshooting, but I always put in the sync code from the mobile app to get back up and running. For reference, when I experimented with my old laptop earlier and it worked, I had manually added a single library card/pin to my Libby desktop browser. Regarding the mobile app, for reference, I did not have it set to automatically download books to my mobile device - personal preference - not sure it mattered one way or the other.
 
2. Expired library card. I have a few library cards. One of them expired back in March 2024; the rest are still active. I didn't manually remove the expired card from my list of library cards in Libby. Expired cards do not automatically remove themselves, and there is no requirement of the user to remove an expired card; thus, I never bothered. I am less inclined to believe this is the true root-cause, because this TypeError had only just started on 4/12/2024. I am prevented from adding my expired library card manually, as mentioned above, in order to test whether this possibility is the true root-cause.

**Comment by blindsamurai777** [comment] 2024-04-14 04:55
NotKoalafied popped in as I was typing up my response. Looks like two people independently arrived at the same answer - add library cards manually after a fresh reset.

**Comment by audiojunky23** [comment] 2024-04-14 15:05
I just tried a fresh install of Firefox and still had the same error

**Comment by blindsamurai777** [comment] 2024-04-14 16:43
audiojunky23 - great to hear that manually re-adding your card(s) resolved the matter. Before, when you received the error, did you have your Libby Firefox desktop browser synced with your Libby mobile app? I'm asking to get a sense if the root-cause of the TypeError is related to syncing issues.

**Comment by NotKoalafied** [comment] 2024-04-14 18:16
@blindsamurai777 tossing in that for me I was trying to sync my browser with my mobile app.

**Comment by mkgtu** [comment] 2024-04-14 18:20
I don't know what happened to "cross posting", but most of the comments re this "Firefox" issue are not appearing in the GitHub issues for the Firefox extension. And all these suggestions about fixing the Firefox problem aren't very helpful re the Chrome extension. 

If all methods of downloading Libby/Overdrive audiobooks were reported "widely" as not working anymore, then I'd say it's obvious that Overdrive/Libby has changed something server side that is blocking all these methods. But I don't see that happening. ALL the methods seem to be working fine for most people on most browsers. And if for some people one method or another isn't working, a bit of "house cleaning" on the user end seems to fix things. (Reinstalling things, resyncing Libby accounts, re-adding cards manually, deleting expired cards, etc).
  But for the most part, all these methods are generally reported as still working. They work for me on six browsers, on both Windows and Android:
 - Libby Audiobook Exporter V2.4 on all six.
 - The Libby (legacy) Audiobook Exporter v1.2.2, on all browsers except Lemur android (and maybe it never worked in Lemur)
 - The Firefox Libby Download ext still works for me. Always has.
 - The old OverDrive "app" still works for downloads on Windows and Android.
 - The Libby Audiobook Bot for Telegram still works without any glitches.
 - And just two days ago I got a reply to an old post on Reddit from a person saying how happy they were to be able to download audiobooks using the old Chrome Video Audio Downloader extension. It's not exactly user friendly and I didn't know anybody was still using it. But I guess it's still working.

So I'm general I'd have to conclude that Libby and Overdrive don't seem to have changed anything server-side, at least not widely. Though it's possible they are rolling out some trial balloons locally.

Firefox is a limited use scenario since it's add-on only works on the desktop browser. But even there it would be helpful to know whether any given issue is on Windows or Max, and whether in the stable version or the Beta or Nightly versions. Also good to know WHERE the problem is occurring (what city, region, country, maybe even which ISP.)

For the Chrome extension, which one? the 2.4 or the legacy 1.2.2? Which browser? And have you tried it on other browsers; there are so many chromium based options. Which platform? Windows, Mac, Android (there are at least 4 chromium based android browsers that allow these extensions - Kiwi, Lemur, Yandex, Mask) And again where are you located? The locations where this is happening may be a clue as to whether Libby is "rolling out" changes.

Without these kind of details, reports of things not working and possible fixes are mostly anecdotal, and real cause/effect linkage is vague or doesn't make sense.

**Comment by mkgtu** [comment] 2024-04-14 18:58
https://github.com/houtianze/libby-audiobook-exporter-browser-extension/issues/13#issuecomment-2053903682

Regarding the two "fixes". Glad it worked for you but I'm not sure WHY it would have worked, except that sometimes a little general housecleaning can fix things in unknown ways 🤣

As to "syncing". You don't sync a browser to a Libby "app". You sync apps, browsers, etc to your Libby "account". When you use that 8 digit code to set up a new app or browser, you can get that code from anywhere. You can get it from a Libby app, but you can also get it from the Libby app.com website in another browser you have already set up. If you manually add cards to a website or app, I suspect those are probably going to "sync" to your account anyway. Not sure, haven't tried it. 

Resetting everything on a device, app, or website probably cures a host of ills. But I don't see "why" manually adding cards, is any different from using the code to sync the cards automatically - unless there is something wrong or corrupt with your account itself. In that case, you can ask Libby to reset your account in their dashboard. I've had to do that once before. It's quite easy. Your cards are not lost in the process. 

As to expired cards. Again, glad it helped, but I don't see how it would affect downloading already borrowed books. You couldn't borrow another book on that card, but books borrowed while the card was still active would remain in your account for the duration of the original loan period and then be returned. Until then you would still be able to listen to them or download them regardless of the status of your card. All these download methods here look for the files of the book you open. They don't examine the status of your account or its cards. If the selected book is open in the webpage, that's enough. These extensions and bots just inspect the current page. 

Again, glad your fixes worked, but "why" they worked is a mystery to me. What is more clear is that given a clear, clean playing field, there seems to be nothing wrong with any of these extensions in themselves. They do work.

**Comment by NotKoalafied** [comment] 2024-04-14 19:09
> I don't see "why" manually adding cards, is any different from using the code to sync the cards automatically

I'm not sure what all the differences are, but I do know that adding a card manually doesn't copy your tags while using the 'copy to another device' feature does. So there is some level of difference in what information is carried over.

**Comment by mkgtu** [comment] 2024-04-14 20:44
> > I don't see "why" manually adding cards, is any different from using the code to sync the cards automatically
> 
> I'm not sure what all the differences are, but I do know that adding a card manually doesn't copy your tags while using the 'copy to another device' feature does. So there is some level of difference in what information is carried over.

I hadn't thought of tags etc that might be missing if the website isn't synced to your Libby account. What else is missing? I can see more disadvantages than advantages in not syncing a particular browser instance to your Libby account on other websites, apps, devices. 
   Also still not sure "why" it would make any difference to the operation of an extension, which is really just inspecting the open webpage looking for loaded file links. Seems to me the extension would care which account it is, or what else it's synced with - just the open page in front of it.
   Before this "manual" adding of cards advice, with all it's possible  disadvantages becomes too widespread, would you mind deleting all your Libby cookies and clearing the cache, in the same browser, thereby logging you out of the website. Then try setting it up again, this time using a setup code, just to see what happens. I think in science circles this is called "falsifying" results. If you can still download a book after a setup code is used, then you have proved that whether you set up a website manually or through account sync has no bearing on the operation of the extension in that particular browser. If you can't download anything, then your previous method may have had an effect - or it may have been a fluke. Try it again, until you can reproduce the same results each time. 
   Try it with the Firefox extension but also with the Chrome extension. This is after all the GitHub page for the Chrome extension, not Firefox. 
   And with the Chrome extension do it with the newer 2.4 version and see what happens. That TypeError message I think is what shows up in the legacy 1.2.2 version, which is actually no longer officially supported anyway, though I find it still works in most browsers.

**Comment by mkgtu** [comment] 2024-04-14 21:44
To further complicate things, earlier today I received a reply from someone who had just installed the 2.4 Chrome extension using code from here (GitHub). But after refreshing the page he kept getting the message that the page needed refreshing. So I replied with some tips and suggestions and also included the suggestions here about starting over with manually entered cards. AND IT WORKED. He just got back to me, happy as a clam, saying he was now successfully downloading, But the catch is he only HAS one library card which is obviously easy to enter manually - even though he may now be missing tags from his account in that browser. BUT I still don't know if entering his card using a setup code would have worked just as well. 
    What is clear is that if there are issues with Libby extensions, then clearing all the Libby cookies, and maybe browser cache, and starting over again may "clear the decks" and fix these issues. But whether it is necessary in these circumstances to manually enter all your card numbers (and possibly lose important synchronized data like tags) instead of simply entering a setup code and re-establishing full account synchronization - that is not clear to me. It needs to be tried out - by trial and error - both ways, before widely recommending this manual re-entering as a fix. 

Here was my Reddit response to this user, including remarks about the legacy extension. He had asked why he should not remove it completely instead of just disabling it. 
https://www.reddit.com/r/audiobooks/s/4TIFdDczUH

**Comment by blindsamurai777** [comment] 2024-04-14 22:10
mkgtu - 

NotKoalafied brought up a great point about the tags. It's an interesting thought since it directly relates to the syncing idea and is quite literally the only discernable difference between manual entry and device syncing from an end-user perspective. Tags are tied to individual devices (e.g., borrowed, returned, other smart tags). When you reset a device (e.g., mobile, web browser, etc.), the tags on that device are no more. Why are tags tied to the device and not the library card? No clue. That's just the way Libby is set up. 

Maybe the code - knowingly or unknowingly - is looking through tags and runs into problems when it can't find them. The "borrowed" tag is automatically assigned by default every time a book is borrowed - known as a "smart tag" - but it can be effectively disabled by switching it to a "regular tag" in accordance with the attached screenshot. 

FYI - While tags are tied to individual devices, the timeline of borrow history is tied to library cards - so independent of device. Why? Not sure but I wanted to make that distinction in case anyone in the future is reading this and gets confused.

---

Now, to address your questions, specifically . . . 

1. I can confirm when I did my extensive troubleshooting, one of the first things I did was clear cache/cookies/history. I made small, incremental, methodical, steps in my troubleshooting process before adding library cards manually as a last resort. Even did a fresh reinstall of Firefox. Nothing worked because I keep syncing my web browser to my mobile app. I was able to repeat the error dozens of times. Technically, I can still repeat the process because I have not reset my mobile app. My mobile app still has all of my old tags and my expired library card attached. In fact, I just reproduced the error again out of curiosity --> entered sync code --> download book --> TypeError. This fix/workaround/solution has proven repeatable dozens of times over, too, for myself. Others attest to it.

**Comment by mkgtu** [comment] 2024-04-15 00:02
> Technically, I can still repeat the process because I have not reset my mobile app.

Seems to me then  you ought to reset your mobile APP by removing your expired card, clearing the data and then maybe log back in by using a setup code from the browser where you've entered everything manually. If you think bad data from your app, including an expired card you haven't removed, is screwing up your browser by transferring problematic info, then get rid of the source of bad info and start over. But don't suggest that everybody else with an extension problem needs to manually enter library cards if it's not necessary in all cases. Setup code first, then manual if needed. And if you have to do it manually for the sake of an extension, then do it on a separate browser you don't use for anything else. Make it your "download" browser and don't care that its  Libby website is out of sync with your other installations. There are plenty of chromium based browsers to  choose from.

I can't recommend manual entry of multiple cards in multiple installations. I have eleven library cards, synced in 16 browsers across 4 devices and 4 apps installed on 4 mobile devices. I'd hate to have to deal with all that manually and get everything out of sync.

**Comment by mkgtu** [comment] 2024-04-15 03:13
I just got a message through Reddit from someone I've been communicating with about this issue in Firefox. I haven't heard from them in a couple of days and never had a chance to offer your suggestion to them, as I did for another person today who found that it worked. 

Anyway, this person came to the same conclusion as you, on their own, with no prompting from me. I don't know if they tried the setup code first, or whether their account has an anomalies like expired cards. 

But here's what they just wrote to me;
  "If anyone else is having the same troubles, I deleted Foxfire, reinstalled and then manually added all my libraries back and it solved the issue." 

One more home run for your side. 👍

**Comment by mkgtu** [comment] 2024-04-15 16:26
I can't agree with your conclusion, especially on this GitHub page which is for the CHROME LIBBY AUDIOBOOK EXPORTER, NOT the FIREFOX LIBBY DOWNLOAD ADD-ON. 

Rather than close this issue, I would suggest that the entire thread be DELETED from this forum. None of you are talking about Hou Tianze's Chrome extension; you're all talking about Firefox and the Firefox extension by bookbonobo, which has its own GitHub page:
https://github.com/bookbonobo/libby-download-extension

That page also has a thread about this issue, entitled "TypeError: o is undefined" and that is where this entire discussion about Firefox and it's extension problem should have been taking place, NOT HERE.

The issues you discuss are about Firefox. The solution/workaround is about how you fixed things in Firefox. Replies I've had in Reddit about the success with manually adding cards all relate to Firefox.

Any discussions I've had recently on Reddit relating to issues with the CHROME extension not working for them were resolved by careful explanation about how to use the extension (and which version). People were just not using the extension correctly or weren't clear on the differences between the way the two versions function (2.4 vs legacy). Nobody I talked to had to re-add cards, manually or otherwise, with the Chrome extension.

Bottom line, this entire thread is for the most part IRRELEVANT to this forum. It's all about Firefox, not Chrome. And I certainly would not "close" it with any sense of satisfaction by offering Firefox "workarounds" in a forum that deals with a Chrome extension. I would suggest, if possible, to cut and paste it all to the proper GitHub page. Or create a post in https://github.com/bookbonobo/libby-download-extension/issues/192
that summarizes this discussion. I did that to some extent last night and included a link to this thread.

Then I'd close/delete this issue, not as "resolved" but as "unrelated" or whatever term is used in this kind of forum to describe an issue that is basically off topic.

To be offering Firefox extension workarounds as the final solution in this Chrome extension forum, especially when this extension may not be experiencing the same issue, is to do a disservice to the Libby Audiobook Exporter Chrome extension and Hou Tianze, its developer.

**Comment by blindsamurai777** [comment] 2024-04-21 11:22
Damn, bro. You are absolutely livid, huh?

**Comment by AIndoria** [comment] 2024-04-22 02:43
> Bottom line, this entire thread is for the most part IRRELEVANT to this forum.

It's not a 'forum' bro, relax.

> None of you are talking about Hou Tianze's Chrome extension;

Yes we are. The exact same error is reproducible on Chrome as well. You should take a chill pill and let people talk, discuss, and sort the issue out.

May I suggest taking a walk?

**Comment by NotKoalafied** [comment] 2024-04-22 02:56
@houtianze if you're ok with it, I recommend closing this thread. It seems to be getting unnecessarily heated and we have issue #12 addressing the same problem.

**Comment by houtianze** [comment] 2024-04-23 01:05
@NotKoalafied OK, I close this for thread. There are a number of reports of the plugin broke, but I currently can't reproduce. It sounds that they may have altered/removed `openbook.json` and thus the break. I will try download again in some time and/or think about how to trace out the cause.

**Closed by houtianze** 2024-04-23 01:05 UTC
